###
PUT http://localhost:3000/api/
Content-type: application/json

{
	"email":"diniusa1@nku.edu",
	"password":"2w94025309d"
}

###
GET http://localhost:3000/api/

###
DELETE http://localhost:3000/api/
